version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "3002:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
volumes:
  postgres_volume:
