version: "3"
services:
  main:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DB_URL: redis://db:6379
  db:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - "db_volume:/data"
volumes:
  db_volume:
